### ISSUE TITLE
Fix fonts

### ISSUE THREAD

**Issue by laurenoutloud** [laurenoutloud/laurenoutloud.github.io#1]
Update fonts so they look nice on both web and mobile

**Comment by amiresp** [comment]
hi @laurenoutloud , are you looking for a related font?

**Comment by laurenoutloud** [comment]
No, I am just having trouble using viewport units to get the font size to look nice on both web and mobile. Either on mobile its too small or on web its too big

**Comment by laurenoutloud** [comment]
This issue was solved by adding `<meta name="viewport" content="width=device-width, initial-scale=1.0">` to index.html.

**Comment by amiresp** [comment]
Yes that's right
I apologize for being late

**Comment by laurenoutloud** [comment]
@amiresp no worries! (:
